### ISSUE TITLE
Request for pretrained model

### ISSUE THREAD

**Issue by luforo99** [lorenzomammana/MSLapSRN-pytorch#2]
I have trained your model with my dataset and obtained lower PSNR (only 27.73dB). So could you share with me your model which obtain the highest PSNR (28.39 dB on Set14x4)! Btw, thank you very much for sharing this MSLapSRN model

**Comment by lorenzomammana** [comment]
Hey @luforo99 thanks for the interest in this repository, I've added the best model to the repository (best.pt) to be honest with my current GPU I can't test if it's the correct one because I go out of memory.

I managed to run the BSD1000 at 2x and the results are the ones I've placed in the readme a while ago so it should be the correct file, let me know.
